POST http://172.18.39.162:20002/user/subscribe_users_status
Content-Type: application/json
operationID: 2134
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxODE2NTI4NzA3IiwiUGxhdGZvcm1JRCI6MywiZXhwIjoxNzAzNTczNTQ1LCJuYmYiOjE2OTU3OTcyNDUsImlhdCI6MTY5NTc5NzU0NX0.4IW02XNoNnN403UtRu7pj-LQu478EAdTB0_huD5roBs

###
